export default {
  GLOBAL_RIGHT_SIDEBAR_TOGGLE: "GLOBAL_RIGHT_SIDEBAR_TOGGLE",
  GLOBAL_RIGHT_SIDEBAR_VIEW_SWITCH: "GLOBAL_RIGHT_SIDEBAR_VIEW_SWITCH",
  GLOBAL_TARGET_USER_SWITCH: "GLOBAL_TARGET_USER_SWITCH",
  GLOBAL_SOCKET_CONNECTION_CLEAR: "GLOBAL_SOCKET_CONNECTION_CLEAR",

  USER_FETCH_TRY_AUTO_SIGNIN: "USER_FETCH_TRY_AUTO_SIGNIN",
  USER_FETCH_SIGNOUT: "USER_FETCH_SIGNOUT",
  USER_FETCH_SIGNIN: "USER_FETCH_SIGNIN",
  USER_FETCH_SIGNIN_SUCCESS: "USER_FETCH_SIGNIN_SUCCESS",
  USER_FETCH_EDIT: "USER_FETCH_EDIT",
  USER_FETCH_EDIT_SUCCESS: "USER_FETCH_EDIT_SUCCESS",

  TEAM_SWITCH: "TEAM_SWITCH",
  TEAM_FETCH_CREATE: "TEAM_FETCH_CREATE",
  TEAM_FETCH_CREATE_SUCCESS: "TEAM_FETCH_CREATE_SUCCESS",
  TEAM_FETCH_EDIT: "TEAM_FETCH_EDIT",
  TEAM_FETCH_EDIT_SUCCESS: "TEAM_FETCH_EDIT_SUCCESS",
  TEAM_FETCH_ASSOCIATED_LIST: "TEAM_FETCH_ASSOCIATED_LIST",
  TEAM_FETCH_ASSOCIATED_LIST_SUCCESS: "TEAM_FETCH_ASSOCIATED_LIST_SUCCESS",
  TEAM_SOCKET_RECEIVE_NEW_MEMBER: "TEAM_SOCKET_RECEIVE_NEW_MEMBER",

  CHANNEL_SWITCH: "CHANNEL_SWITCH",
  CHANNEL_FETCH_EDIT: "CHANNEL_FETCH_EDIT",
  CHANNEL_FETCH_EDIT_SUCCESS: "CHANNEL_FETCH_EDIT_SUCCESS",
  CHANNEL_FETCH_CREATE: "CHANNEL_FETCH_CREATE",
  CHANNEL_FETCH_CREATE_SUCCESS: "CHANNEL_FETCH_CREATE_SUCCESS",
  CHANNEL_FETCH_ASSOCIATED_LIST: "CHANNEL_FETCH_ASSOCIATED_LIST",
  CHANNEL_FETCH_ASSOCIATED_LIST_SUCCESS:
    "CHANNEL_FETCH_ASSOCIATED_LIST_SUCCESS",

  MESSAGE_FETCH_MORE: "MESSAGE_FETCH_MORE",
  MESSAGE_FETCH_MORE_SUCCESS: "MESSAGE_FETCH_MORE_SUCCESS",
  MESSAGE_SOCKET_RECEIVE: "MESSAGE_SOCKET_RECEIVE",

  ERROR_AUTH: "ERROR_AUTH",
  ERROR_USER: "ERROR_USER",
  ERROR_TEAM: "ERROR_TEAM",
  ERROR_CHANNEL: "ERROR_CHANNEL",
  ERROR_MESSAGE: "ERROR_MESSAGE",
  ERROR_CREATE: "ERROR_CREATE",
  ERROR_ALL_CLEAR: "ERROR_ALL_CLEAR"
};
