export default {
  /* users */
  AUTO_LOGIN: "AUTO_LOGIN",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  AUTH_ERROR: "AUTH_ERROR",

  /* team */
  CREATE_TEAM: "CREATE_TEAM",
  GET_TEAM_ASSOCIATED_LIST: "GET_TEAM_ASSOCIATED_LIST",
  ADD_TEAM_MEMBER: "ADD_TEAM_MEMBER",
  TEAM_ERROR: "TEAM_ERROR",

  /* team */
  CREATE_CHANNEL: "CREATE_CHANNEL",
  CHANNEL_ERROR: "CHANNEL_ERROR"
};
