export default {
  /* global state */
  TOGGLE_SIDE_BAR: "TOGGLE_SIDE_BAR",

  /* users */
  AUTO_LOGIN: "AUTO_LOGIN",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",

  /* team */
  CREATE_TEAM: "CREATE_TEAM",
  SWITCH_TEAM: "SWITCH_TEAM",
  GET_TEAM_ASSOCIATED_LIST: "GET_TEAM_ASSOCIATED_LIST",
  ADD_TEAM_MEMBER: "ADD_TEAM_MEMBER",
  GET_CURRENT_TEAM: "GET_CURRENT_TEAM",

  /* channel */
  CREATE_CHANNEL: "CREATE_CHANNEL",
  SWITCH_CHANNEL: "SWITCH_CHANNEL",
  GET_CURRENT_CHANNEL: "GET_CURRENT_CHANNEL",
  GET_CHANNEL_ASSOCIATED_LIST: "GET_CHANNEL_ASSOCIATED_LIST",
  SEND_MESSAGE: "SEND_MESSAGE",

  /* message */
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  CLEAR_SOCKET_CONNECTION: "CLEAR_SOCKET_CONNECTION",
  FETCH_MORE_MESSAGE: "FETCH_MORE_MESSAGE",

  /* error */
  AUTH_ERROR: "AUTH_ERROR",
  TEAM_ERROR: "TEAM_ERROR",
  CHANNEL_ERROR: "CHANNEL_ERROR",
  MESSAGE_ERROR: "MESSAGE_ERROR",
  UPLOAD_ERROR: "UPLOAD_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR"
};
