export default {
  /* users */
  AUTO_LOGIN: "AUTO_LOGIN",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  AUTH_ERROR: "AUTH_ERROR",

  /* team */
  CREATE_TEAM: "CREATE_TEAM",
  CREATE_TEAM_ERROR: "CREATE_TEAM_ERROR"
};
